# Task1

In [2]:
import numpy as np

In [12]:
a = np.array([[0.05, 0.07, 0], [0.05, 0, 0.06], [1, 1, 1]])
b = np.array([2250, 1400, 50000])
x = np.linalg.solve(a, b)
print(x)

[10000. 25000. 15000.]


# Task2

In [ ]:
x - y + z*0 = -120
x + y*0 - z = 100
x + y + z = 1328

In [13]:
a = np.array([[1, -1, 0], [1, 0, -1], [1, 1, 1]])
b = np.array([-120, 100, 1328])
x = np.linalg.solve(a, b)
print(x)

[436. 556. 336.]


# Task3

In [ ]:
3/a**2 + 0/b**2 + 3/c**2 = 1
6/a**2 + 1/4b**2 + 0/c**2 = 1
1/a**2 + 1/3b**2 + 1/c**2 = 1

In [25]:
a = np.array([[3, 0, 3], [6, 1/4, 0], [1, 1/3, 1]])
b = np.array([1, 1, 1])
x = np.linalg.solve(a, b)

a_sq = round(1/x[0], 2)
b_sq = round(1/x[1], 2)
c_sq = round(1/x[2], 2)

print(a_sq, b_sq, c_sq)


12.0 0.5 4.0


# Task4

In [ ]:
1*a + 1*b + 1*c = 12
9*a + 3*b + 1*c = 54
1*a - 1*b + 1*c = 2

In [30]:
a = np.array([[1, 0, 1], [9, 3, 1], [1, -1, 1]])
b = np.array([12, 54, 2])
x = np.linalg.solve(a, b)
print(x)

[ 1.5 10.  10.5]


# Task5

In [49]:
def get_polynom(cords):
    b = np.array([x[1] for x in cords])
    a = []
    power = len(cords)
    for row in range(power):
        x = cords[row][0]
        cord_list = [x**pow for pow in reversed(range(power))]
        a.append(cord_list)
    a_mtx = np.array(a)
    return np.linalg.solve(a_mtx, b)

get_polynom([(1,12), (3,54), (-1,2)])


array([4., 5., 3.])